### ISSUE TITLE
Need better README

### ISSUE THREAD

**Issue by dleggo** [dleggo/Dalix#1]
The current README just links to the [homepage](dleggo.github.io/Dalix). We should improve this to provide information on Dalix, and then after that, then provide a link to the homepage.

**Comment by sudoAPWH** [comment]
The idea for DalixOS is that the simplicity should be noticed immediately. It will use a simplified folder setup that just makes sense! “System” for important files, “Applications” for apps, and “Users” for your files. It’s what everything you need and nothing that you don’t!

DalixOS’s stability will be clear from the first use. The special file system keeps essential files safe, which will let you run multiple app versions without conflict. Installing new software should be a breeze. Drop an Application into the “Applications” folder, and DalixOS should convert it into a  App-Bundle, installing any dependencies automatically. 
It's everything you need and nothing that you don't! Letting you do what you need, without “Un-User-Friendly” package managers!


DalixOS will also auto clean up unused dependencies so your disk isn’t filled up with unused files!

The goal for DalixOS is is to be organized, stable, and user friendly and an OS that just works.

**Comment by dleggo** [comment]
Nice! Want to make a PR from this?
