### ISSUE TITLE
Make a better homepage

### ISSUE THREAD

**Issue by dleggo** [dleggo/Dalix#3]
The [homepage](https://dleggo.github.io/Dalix) is really dull. Pointing only to the FAQ and Misc, it really needs a redo. It should be more detailed then the README, and more end-user oriented. If you popped an average-joe in front of our homepage could they understand how to use Dalix? That is the purpose of the homepage.

**Comment by sudoAPWH** [comment]
I was thinking of replacing this:

 An OS (based on Linux, but don't let that scare you) which aims to have a UI with the quality of the early MacOS's. FHS not included

With this: 

A Linux based operating system designed to have a user interface reminiscent of macOS, prioritizing user-friendliness and looks. Note: FHS is not included.

**Comment by dleggo** [comment]
Good suggestion! But please put any off-topic statements into [discussions](https://github.com/dleggo/Dalix/discussions) instead of in an issue. Thanks.

**Comment by sudoAPWH** [comment]
Prospect homepage below!

Meet DalixOS! A project which aims to make a MacOS like experience for Linux. This is not your traditional Linux distro as it completly abandons the FHS

We want you to have a almost “Drop-In” replacement for macOS! Below is a list that has the top few of the features on Dalix that will be imitating the macOS look/feel!

Window Buttons: Are you used to macOS’s easy to use window buttons? DalixOS will be embracing that feature!

macOS Dock: macOS users love their dock, so will Dalix users!

Launchpad: One of macOS 11 and later best features, it allows you with one click on your dock, to access a tablet-like application list! Dalix will be having that feature for sure!

A few more, Global menu, control centre, spatial finder, and where application dependency’s auto-install!

**Comment by dleggo** [comment]
Good ideas! The one thing I should say is that Launchpad may not be implemented, and either way, referencing the **tabletization** of the computer is how flame-wars are started on the internet. ```;)```

**Comment by sudoAPWH** [comment]
I was also thinking of adding in certain parts of the homepage…

**Comment by dleggo** [comment]
Sorry, I'm not sure I understand what you mean? Could you clarify?

**Comment by sudoAPWH** [comment]
And anyway, if there won’t be a launch pad, there does need to be some sort of application search…. User should not have to go to Applications in files every time they need to open an app….
Maybe implement something like the Mac  “Cmd Space” thing?

**Comment by sudoAPWH** [comment]
> Sorry, I'm not sure I understand what you mean? Could you clarify?

Whoopsie, sent that before I was ready…. I mean putting parts of the README into the homepage.

**Comment by dleggo** [comment]
There may be launchpad, it has not been discussed, however. Feel free to create a discussion about the prospect of launchpad if you are interested, as we are at the risk of going off topic. I do like your idea for the homepage, but it does sound a little bit too excited if you know what I mean? Maybe a few less exclamation marks? Just a thought.

**Comment by sudoAPWH** [comment]
Yea ;)
Here is an updated version!

Meet DalixOS! A project which aims to have a stunning macOS like appeal bringing the macOS like experience to Linux! This is not your traditional Linux distro as it completly abandons the FHS.

We want you to have a almost “Drop-In” replacement for macOS! Below is a list that has the top few of the features on Dalix that will be imitating the macOS look/feel.

Window Buttons: Lots of people you used to macOS’s easy to use window buttons, DalixOS will be having that feature.

macOS Dock: macOS users love their dock, we will be working on implementing that feature into Dalix.

A few more, Global menu, control centre, spatial finder, and where application dependency’s auto-install.



**The goal for DalixOS is is to be organized, stable, and user friendly and an OS that just works.**

**Comment by dleggo** [comment]
Some edits...

Meet DalixOS! A project which aims to have a stunning macOS like appeal bringing the macOS like experience to Linux! This is not your traditional Linux distro as it abandons the FHS as much as possible implementing human readable paths.

We want you to have an almost “Drop-In” replacement for macOS! Below is a list of the top features of Dalix that will be imitating the macOS look/feel.

Window button trafic lights ```:D```: More of a preference thing, but still nice nonetheless.

Dock: macOS users love their dock, we will be working on implementing that into Dalix.

And a few more including, but not limited to, Global menu bar, control center, spatial finder, and automatic dependency resolving without breakage.

**The goal for DalixOS is is to be organized, stable, and user friendly and be an OS that just works.**

**Comment by sudoAPWH** [comment]
Perfect!
